### ISSUE TITLE
Compatibility issues with adrenaline

### ISSUE THREAD

**Issue by mathieulh** [SKGleba/psp2renga#2]
I haven't had quite the chance to look in details so I do not know if either 0syscall6 or renga itself causes this issue, but when renga and the renga version of the 0syscall6 plugin are activated (I am using it with the 3.73 kprx_auth_sm if that changes anything), adrenaline crashes whenever I try to run it, if I disable both renga and 0syscall6 plugins, adrenaline runs just fine.

(moved from https://github.com/SKGleba/0syscall6/issues/2 )

**Comment by SKGleba** [comment]
Nop, it happ3ns even without any entry, gonna investigate if its a SRAM issue

**Comment by SKGleba** [comment]
Camera SRAM-related problem, gonna try to fix it.

**Comment by SKGleba** [comment]
Ok, the issue was fixed, an updated version is already on private repo, i will push it with fixes for https://github.com/SKGleba/psp2renga/issues/1
