### ISSUE TITLE
European version of Ar No Surge opening movie has no sound when using the renga version

### ISSUE THREAD

**Issue by mathieulh** [SKGleba/psp2renga#3]
I am unsure if it's entirely related but the European version of Ar No Surge (PCSB00798) opening movie has no sound when using the renga version with 3.73 kprx_auth_sm, the problem does not occur using either the standalone version of 0syscall6 or ref00d.

Initially created on https://github.com/SKGleba/0syscall6/issues/9, opened here on request.

I have not changed/forced the mode to SRAM or PHYCONT so this is using whatever the 0syscall6 module uses by default.

**Comment by SKGleba** [comment]
Please change to SRAM and retry.

**Comment by SKGleba** [comment]
(Add the _forcesram)
